theme: jekyll-theme-minimal
title: "Shemelis Kebede Hundie"
description: "Personal website of Shemelis K. Hundie."

# Disable the automatic GitHub profile link
github:
  is_project_page: false
  repository: false
  show_github: false
show_downloads: false

navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Research"
    url: /research
  - title: "Projects"
    url: /projects
  - title: "CV"
    url: /CV
  - title: "Social Media Profiles"
    url: /social
